### ISSUE TITLE
Looking to learn and contribute

### ISSUE THREAD

**Issue by voduku** [rsocket-routing/rsocket-routing-broker#22]
Hi, I am looking forward to seeing V1.0.0 releases of this project (rsocket-routing). Are you guys looking for unpaid intern? I would love to be a contributor too but I am afraid that I don't have enough experience.

**Comment by Ace931124** [comment]
Oh,I have the same idea

**Comment by VuDo98** [comment]
I don't know if we will get a response haha

**Comment by spencergibb** [comment]
The documentation is where it would be easiest to contribute without much experience
